name: Planfi Front

on:
  workflow_dispatch:

env:
  API_URL: "http://localhost:8081"
  Domain: "plan-fi.pl"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - uses: actions/checkout@v2

      - uses: microsoft/variable-substitution@v1
        with:
          files: "Planfi.Front/config.json"
        env:
          apps.PlanfiApi.url: ${{ env.API_URL }}

      - uses: actions/checkout@v2

      - name: Build and deploy frontend to static GCP Cloud Storage
        run: |
          cd ./Planfi.Front/
          npm install
          CI=false npm run-script build
          gsutil web set -m index.html -e index.html gs://${{ env.Domain }}
          gsutil iam ch allUsers:legacyObjectReader gs://${{ env.Domain }}
          gsutil -h "Cache-Control:public, max-age=60, no-transform" rsync -d -r ./build gs://${{env.Domain}}/

      #create bucket - aready exist already after 1 execution
      #gsutil mb -p ${{secrets.GCP_PROJECT_ID}} -b on gs://${{ env.Domain }}
      # allow everyone to see your website
      # gsutil -m acl ch -R -u AllUsers:R gs://example.ack.ee

      # set the webserver index and error page
      # gsutil -m web set -m index.html -e index.html gs://example.ack.ee 
