name: Planfi Front

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  API_URL: "https://planfi-api-g3lfmgrpmq-uc.a.run.app"
  Domain: "plan-fi.pl"
  BUCKET: "planfi"
  ENVIRONMENT: true

jobs:
  cypress-run:
      runs-on: ubuntu-latest
      steps: 
        - name: Checkout
          uses: actions/checkout@v2
        - name: Install node
          uses: actions/setup-node@v2
          with:
              node:version: '14'
        - uses: cypress-io/github-action@v2
        - name: Install dependencies
          run: |
            cd ./Planfi.Front/
            Cypress run


  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - uses: actions/checkout@v2

      - uses: microsoft/variable-substitution@v1
        with:
          files: "Planfi.Front/config.json"
        env:
          apps.PlanfiApi.url: ${{ env.API_URL }}
          apps.PlanfiApi.isProduction: ${{ env.ENVIRONMENT }}

      - name: Read config.json from Planfi.Front
        run: "cat Planfi.Front/config.json"

      - name: Build and deploy frontend to static GCP Cloud Storage
        run: |
          cd ./Planfi.Front/
          npm install
          CI=false npm run-script build
          gsutil web set -m index.html -e index.html gs://${{ env.BUCKET }}
          gsutil iam ch allUsers:legacyObjectReader gs://${{ env.BUCKET }}
          gsutil -h "Cache-Control:public, max-age=0, no-transform" rsync -d -r ./build gs://${{env.BUCKET}}
          gcloud compute url-maps invalidate-cdn-cache planfi-lb --path '/${{env.Domain}}/*'